### ISSUE TITLE
Planning on supporting primus-rooms?

### ISSUE THREAD

**Issue by PedroMD** [neoziro/angular-primus#13]
Ey, thanks for this!

It seems there is no rooms (plugin here: https://github.com/cayasso/primus-rooms) support, right? Would be great to turn this into an ng wrapper for Primus.io (https://www.npmjs.com/package/primus.io) which already supports emitter (implemented already), rooms and multiplexer. 

Are you planning on making this compatible with primus-rooms any time soon? 

Cheers!

**Comment by tranquilo** [comment]
Hey, i did make a pull request with multiplexing and room support.
You can check it out here: [https://github.com/tranquilo/angular-primus](https://github.com/tranquilo/angular-primus)

Thanks

**Comment by PedroMD** [comment]
Hey, thanks! 
Just checked it and I can only see multiplexing support. There is not a single reference to rooms...right?

**Comment by tranquilo** [comment]
Check the last lines of the usage instructions:
```
// Subscribe to a channel named "Party" using primus-multiplex
  var channel = primus.$channel('Party');

  // Listen 'data' event on the channel
  channel.$on('data', function(data) {
    console.log(data);
  });
  
```

**Comment by PedroMD** [comment]
AFAIK, channels are what socket.io calls namespaces. Rooms, on the other hand, are a totally different thing - it does not multiplex the single connection, like namespaces, but instead just gathers all socket ids in a common array, making communication with a set of connected clients much easier to implement. Rooms would be great for my app scenario, not channels or namespaces... Am I right, or am I missing something?!

**Comment by tranquilo** [comment]
Yes, it seems socket.io namespaces would be the same as primus-multiplex channels. Channels on socket.io seem to be implemented on top of Namespaces. If your purpose is to "making communication with a set of connected clients much easier to implement" then you have the same functionality with "Sparks" (instead of "Sockets") on primus-multiplex.
Hope this helps.

Cheers

**Comment by tranquilo** [comment]
If primus-multiplex still doensn't provide what you need, then you can take a look at [primus-rooms](https://github.com/cayasso/primus-rooms).

Cheers

**Comment by PedroMD** [comment]
Although primus-multiplex's channel.write(message) would allow me to write to only those connected to the specific channel, it is not the same as rooms :) My rooms must be created dynamically whereas channels are hard-coded whenever the server initiates. In other words, rooms are the much needed stateless logic for my needs.

Yes, primus-rooms is what I need, as I've said initially - I was just trying to find a better way to properly use it right away on my Angular project :)

**Comment by tranquilo** [comment]
I see. You can always do the same as i did and implement it!
But don't forget to share it with us! :)

Good luck with your project.
Cheers

**Comment by PedroMD** [comment]
Yup, I might do so! Thanks ;)

**Comment by PedroMD** [comment]
Hm, looks like it wont be necessary... Room support is server-side only. All I need to do on the fend is send a specific data obj when using .write() and the server will handle joining and leaving and the proper re-transmission of messages...

**Comment by neoziro** [comment]
This plugin is no longer supported, Angular 2 is out.
