### ISSUE TITLE
Primus configuration and $location

### ISSUE THREAD

**Issue by chrismbeckett** [neoziro/angular-primus#3]
Running into the issue where I need to get the current browser URL to be able to set the Primus endpoint, but you can't inject $location into .config. Any suggestions?

UPDATE: Another potential problem - I am trying to use token authentication with the socket server. Seems the only way to do that is to add the token to the connection string, so I need to hold off configuring the socket connection until the user logs into my app.

**Comment by neoziro** [comment]
Yes I know it's a problem, I have two solutions: 

- The quick fix, you can just use window.location and do things without Angular
- The best fix is to be able to configure a locationProvider that will call a service, just like interceptors for $http service. This will involve some refactoring in this library and I don't have time to do that, but feel free to do it and I will merge the PR.

**Comment by chrismbeckett** [comment]
Thanks for the update. Given the emerging Angular 2 direction and the absence of the whole provider pattern anyway, I just wrote my own Primus service that takes a configuration constant.

**Comment by neoziro** [comment]
@chrismbeckett OK thanks
