### ISSUE TITLE
primusProvider.setEndPoint is not a function ?? 

### ISSUE THREAD

**Issue by panbhatt** [neoziro/angular-primus#9]
HI Team,
 I am trying to use this module with Angular 1.4.3 however unable to sync with angular. Everytime when i include this project in the our application.js the following error popped up. 
Uncaught Error: [$injector:modulerr] Failed to instantiate module mfpNotify due to:
TypeError: primusProvider.setEndPoint is not a function

I checked out to see that .setEndPoint is present inside the module. 
Env: Chrome

Can anyone faced the same problem.

**Comment by tranquilo** [comment]
Hey there, im not from the team but, it seems maybe you are not using SetEndPoint function on your module config block, after injecting angular-primus on your application.

**Comment by panbhatt** [comment]
As soon i write this function within the config function of my application it blows up giving the above error. This is what i calling.
primusProvider.setEndPoint(HOST);

**Comment by tranquilo** [comment]
Did you inject primusProvider on the config function?
ex:
    .config(function (primusProvider)

**Comment by panbhatt** [comment]
Yes that is right. I have more providers with this, so this provider is the last.. E.g.
.config(
        function (
            $provide,
            $httpProvider,
             $translateProvider,
            $routeProvider,
            $locationProvider,
            primusProvider
        ){

**Comment by tranquilo** [comment]
Just to exclude, could you show your .module injections?

**Comment by panbhatt** [comment]
(function() {
    var app = angular.module('Sample', [
        "ngMessages",
        "ngSanitize",
        "genderFilter",
        "capitalizeFilter",
        "ngRoute",
        "routeStyles",
        "ui.bootstrap",
        "angularChart",
        "siTable",  // For Si-table this has been added
        "pascalprecht.translate",
        "angularjs-dropdown-multiselect",
        "mfpIframe",
        "mfpModal",
        "primus"
    ], function() {

    }).config(
        function (
            $provide,
            $httpProvider,
            MFPConfig,
            $translateProvider,
            $routeProvider,
            $locationProvider,
            $sceProvider,
            primusProvider
        ){

**Comment by tranquilo** [comment]
Since angular is complaining about: "Uncaught Error: [$injector:modulerr] Failed to instantiate module mfpNotify", maybe it's some problem/conflict with those mfp modules? I would probably try running them separately to see if the problem is from mfp or from primus. I would probably guess its from the first since he's the one throwing the error.
Sorry if i couldn't be of assistance. Good luck mate.

**Comment by panbhatt** [comment]
Closing this bug. as we found out the error. This is related to the way we have used it. This module is working totally fine.
